apiVersion: v1
entries:
  opa:
  - apiVersion: v1
    appVersion: 0.15.1
    created: "2021-02-25T19:40:55.280828526Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 82337d30ce6cd3e59acabdc057b4ef65c52b2c4190e94b038c21afd585962658
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - https://open-policy-agent.github.io/kube-mgmt/charts/opa-1.14.6.tgz
    version: 1.14.6
  - apiVersion: v1
    appVersion: 0.15.1
    created: "2021-02-25T19:40:55.27979079Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 480b39da0fa70dc289fda9607bb9f5e39b6627967bb9bf67321abc0ee8ad9b89
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    maintainers:
    - email: torinsandall@gmail.com
      name: tsandall
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    urls:
    - https://open-policy-agent.github.io/kube-mgmt/charts/opa-1.14.0.tgz
    version: 1.14.0
generated: "2021-02-25T19:40:55.278162033Z"
